import SellerSidebar from "@/components/seller/SellerSidebar";
import { Nunito_Sans } from "next/font/google";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
});

export const metadata = {
  title: "Seller Dashboard",
  description: "Generated by create next app",
};

export default function SellerLayout({ children }) {
  return (
    <div className={`flex mt-8 bg-gray-100 ${nunito.className}`}>
      {/* Sidebar */}
      <SellerSidebar />

      {/* Content Area */}
      <main className="flex-1 p-6 bg-white shadow-md ml-64">{children}</main>
    </div>
  );
}
